name: Code style

on: [pull_request]

jobs:
  lint:
    name: Rubocop linters
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # Due to https://github.com/actions/runner/issues/849, we have to use quotes for '3.0'
        ruby: ['2.7', '3.0', '3.1', '3.2']
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v3
        with:
          bundler-cache: true
      - name: rubocop
        run: bundle exec rubocop --parallel
